name: Sync Leetcode to Git

on:
  workflow_dispatch: # Allows you to run it manually anytime
  schedule:
    - cron: '0 8 * * *' # Runs automatically every day at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          filter-duplicate-secs: 86400
          destination-folder: submissions
